### ISSUE TITLE
invalid memory address or nil pointer dereference - SIGSEGV

### ISSUE THREAD

**Issue by koen84** [binance-chain/bsc#121]
#### System information

Geth version: https://github.com/binance-chain/bsc/releases/download/v1.0.6/geth_linux
OS & Version: Ubuntu 18.04 LTS

#### Expected behaviour
BSC node continues to sync blocks

#### Actual behaviour
Crashes with sigsegv

#### Steps to reproduce the behaviour
Synced blockchain data (btrfs send-receive) from server 1 to server 2.
Wait for data analysis to finsih.
Watch it crash loop.

(I've done a similar procedure on a partially synced chain, but then didn't encounter this bug.)

#### Backtrace

````
INFO [03-23|03:04:09.493] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xe31fac]
goroutine 406 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xefa8872000, 0xefc26771d0, 0xef45187680, 0x0, 0x0, 0xa)
        /server/bsc/eth/downloader/downloader.go:877 +0x158c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xefa8872000, 0xefc26771d0, 0x96bcf84b944613a8, 0xb2b2a12ab092099b, 0xfd3bd72522c01c4f, 0x3a5ff90424fb64bd, 0x113240493e0, 0x0, 0x0)
        /server/bsc/eth/downloader/downloader.go:443 +0x3df
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xefa8872000, 0xdb36f6c500, 0x10, 0x96bcf84b944613a8, 0xb2b2a12ab092099b, 0xfd3bd72522c01c4f, 0x3a5ff90424fb64bd, 0x113240493e0, 0x0, 0x0, ...)
        /server/bsc/eth/downloader/downloader.go:411 +0x37a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xefa8872000, 0xdb36f6c500, 0x10, 0x96bcf84b944613a8, 0xb2b2a12ab092099b, 0xfd3bd72522c01c4f, 0x3a5ff90424fb64bd, 0x113240493e0, 0x0, 0x0, ...)
        /server/bsc/eth/downloader/downloader.go:323 +0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).doSync(0xea9c2280f0, 0x113240708c0, 0x17fdcd0, 0xecdbe3a410)
        /server/bsc/eth/sync.go:289 +0x98
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xefa882cc00, 0x113240708c0)
        /server/bsc/eth/sync.go:283 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        /server/bsc/eth/sync.go:283 +0x76

````

Could be this bug that's not pached in bsc-geth ?
https://github.com/ethereum/go-ethereum/issues/19590

**Comment by guagualvcha** [comment]
The patch is included in bsc release v1.0.6, I think it is a same issue to https://github.com/ethereum/go-ethereum/issues/22502

**Comment by koen84** [comment]
I'm on 1.0.6 and it crashed MUCH faster than that linked issue.

**Comment by guagualvcha** [comment]
It is fixed in https://github.com/binance-chain/bsc/pull/409
