### ISSUE TITLE
Cannot query bsc node on local network via rpc

### ISSUE THREAD

**Issue by LoudMurmur** [binance-chain/bsc#125]
Hi, at first I made a local node in WSL and was able to query it via http://localhost:8545, then I made the same node in a ubuntu server in my local network (firewall is disabled) on an other machine, and launched it with :

sudo ~/bsc/build/bin/geth --config ~/bsc/config.toml --datadir /mnt/ssd/bsc_data/ --pprofaddr 0.0.0.0 --cache=2048 --metrics --pprof --syncmode "fast" --rpc --rpcaddr 0.0.0.0

However I cannot connect to it via http://192.168.1.89:8545 using web3, I'm getting requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.89', port=8545): Max retries exceeded with url

#### System information

Geth version: last commit of this repo, hash : 0e2c471a94d85acd899494b6217dd6b2eae52b07
OS & Version: Ubuntu server x64 ARM 20.10
Commit hash : (if `develop`) : 0e2c471a94d85acd899494b6217dd6b2eae52b07

**Firewall is disabled, sudo ufw status returns : "Status: inactive"**

#### Expected behaviour

w3.eth.blockNumber returns the latest block number

#### Actual behaviour

Web3 cannot establish connection

#### Steps to reproduce the behaviour

Follow this guide https://docs.binance.org/smart-chain/developer/fullnode.html and try to query your node from an other computer of the same network with 
````
from web3 import Web3, HTTPProvider
from web3.middleware import geth_poa_middleware
bsc_node = "192.168.1.89"
w3 = Web3(HTTPProvider('http://{}:8545'.format(bsc_node)))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
print(w3.eth.blockNumber)
````

#### Backtrace

````
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Python36\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Python36\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Python36\lib\site-packages\urllib3\connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001D9F85F2320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python36\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Python36\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.89', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9F85F2320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/checkouts/bsc_node_analyser/test_get_last_bloc_local.py", line 13, in <module>
    latest_block_num = w3.eth.blockNumber
  File "C:\Python36\lib\site-packages\web3\eth.py", line 215, in blockNumber
    return self.block_number
  File "C:\Python36\lib\site-packages\web3\eth.py", line 207, in block_number
    return self._block_number()
  File "C:\Python36\lib\site-packages\web3\module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "C:\Python36\lib\site-packages\web3\manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\middleware\gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\middleware\normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\middleware\exception_retry_request.py", line 104, in middleware
    return make_request(method, params)
  File "C:\Python36\lib\site-packages\web3\providers\rpc.py", line 95, in make_request
    **self.get_request_kwargs()
  File "C:\Python36\lib\site-packages\web3\_utils\request.py", line 39, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.89', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9F85F2320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

Process finished with exit code 1

````

**Comment by dsbaars** [comment]
Does attaching to the geth console using your LAN IP work on the same machine? `geth attach http://192.168.1.89:8545`
Did you try changing your `config.toml` instead of using attributes? **Very insecure** example below:
````
[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSHost = "0.0.0.0"
WSOrigins = ["*"]
WSModules = ["net", "web3", "eth"]
GraphQLHost = "0.0.0.0"
GraphQLPort = 8557
GraphQLVirtualHosts = ["*"]
````

**Comment by guagualvcha** [comment]
hi, @LoudMurmur  it looks like a local setting issue, I am going to close this, if you have any further question feel free to raise new one, thanks.
