### ISSUE TITLE
Panic when syncing with testnet

### ISSUE THREAD

**Issue by DylanVerstraete** [binance-chain/bsc#156]
Hi, my lightclient nodes are mostly stuck on `looking for peers` since this morning. I also randomly receive panics on my nodes that are syncing with testnet:

stacktrace
```
INFO [04-19|12:26:05.918] Block synchronisation started 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf4cecd]

goroutine 6529 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc000d7c380, 0xc004544ff0, 0xc012e726c0, 0x0, 0x0, 0xa)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/eth/downloader/downloader.go:877 +0x13ed
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000d7c380, 0xc004544ff0, 0xc5507b341fd27e77, 0x788c3d7e36c33e61, 0xc2504e0a9c01f6ae, 0xb3cd9f6204d441b, 0xc000160520, 0x0, 0x0)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/eth/downloader/downloader.go:443 +0x3ee
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc000d7c380, 0xc001cd2200, 0x40, 0xc5507b341fd27e77, 0x788c3d7e36c33e61, 0xc2504e0a9c01f6ae, 0xb3cd9f6204d441b, 0xc000160520, 0x2, 0x0, ...)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/eth/downloader/downloader.go:411 +0x37a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc000d7c380, 0xc001cd2200, 0x40, 0xc5507b341fd27e77, 0x788c3d7e36c33e61, 0xc2504e0a9c01f6ae, 0xb3cd9f6204d441b, 0xc000160520, 0x2, 0xc0016eed70, ...)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/eth/downloader/downloader.go:323 +0x8e
github.com/ethereum/go-ethereum/les.(*clientHandler).synchronise(0xc00146f630, 0xc000ca4fc0)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/les/sync.go:181 +0x673
github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3.1(0x1b8c6f8, 0xc000ca4fc0, 0xc0002b1ea0)
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/les/fetcher.go:509 +0x91
created by github.com/ethereum/go-ethereum/les.(*lightFetcher).newFetcherDistReqForSync.func3
	/home/dylan/go/pkg/mod/github.com/binance-chain/bsc@v1.0.7/les/fetcher.go:506 +0xb5
```

**Comment by DylanVerstraete** [comment]
Another more extensive panic stacktrace:

https://gist.github.com/DylanVerstraete/85d2891a232c193334ae1da7d1b14a19

**Comment by huangsuyu** [comment]
which version of `geth` did you use?

**Comment by DylanVerstraete** [comment]
@huangsuyu I don't use `geth`, I am syncing with a lightclient using binance-chain/bsc v1.0.7 lightclient

**Comment by huangsuyu** [comment]
@DylanVerstraete  please share your start command

**Comment by DylanVerstraete** [comment]
You can find our source code here:

https://github.com/threefoldfoundation/tft-stellar/blob/5c125abaf0dfe365678dbcb97592c119377b2315/eth-bridge/api/bridge/client.go#L110

**Comment by HaoyangLiu** [comment]
Could you provide detailed steps and necessary code to reproduce this issue?

**Comment by guagualvcha** [comment]
Fixed in https://github.com/binance-chain/bsc/pull/409
