### ISSUE TITLE
BSC can not gracefull shutdown

### ISSUE THREAD

**Issue by guagualvcha** [binance-chain/bsc#232]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
```
fatal error: concurrent map read and map write

goroutine 1174638587 [running]:
runtime.throw(0x16a9e0f, 0x21)
        runtime/panic.go:1117 +0x72 fp=0xc03d0f3e98 sp=0xc03d0f3e68 pc=0x44f1f2
runtime.mapaccess2(0x148d5a0, 0xc01bcef680, 0xc03d0f3f30, 0x27c86a0, 0x1af9c00)
        runtime/map.go:469 +0x255 fp=0xc03d0f3ed8 sp=0xc03d0f3e98 pc=0x4262d5
github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc015e32000, 0xd896a55ad5f3378c, 0xb8762c019361b270, 0x9a39c7b46f260255, 0x5a85e51f6b6c9ef5, 0x1ae8098, 0xc258749230, 0xc4c43b9090, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/trie/database.go:764 +0x74 fp=0xc03d0f3fc0 sp=0xc03d0f3ed8 pc=0x7c8d74
github.com/ethereum/go-ethereum/trie.(*Database).commit.func1(0xd896a55ad5f3378c, 0xb8762c019361b270, 0x9a39c7b46f260255, 0x5a85e51f6b6c9ef5)        github.com/ethereum/go-ethereum/trie/database.go:771 +0x85 fp=0xc03d0f4030 sp=0xc03d0f3fc0 pc=0x7e3ea5
github.com/ethereum/go-ethereum/trie.forGatherChildren(0x1ad0468, 0xc36bfafcf8, 0xc03d0f44a0)
        github.com/ethereum/go-ethereum/trie/database.go:206 +0x258 fp=0xc03d0f41c0 sp=0xc03d0f4030 pc=0x7c3df8
github.com/ethereum/go-ethereum/trie.forGatherChildren(0x1ad0490, 0xc13fd3d560, 0xc03d0f44a0)
        github.com/ethereum/go-ethereum/trie/database.go:203 +0xe5 fp=0xc03d0f4350 sp=0xc03d0f41c0 pc=0x7c3c85
github.com/ethereum/go-ethereum/trie.(*cachedNode).forChilds(0xc269a7ff80, 0xc03d0f44a0)
        github.com/ethereum/go-ethereum/trie/database.go:191 +0x110 fp=0xc03d0f4400 sp=0xc03d0f4350 pc=0x7c3b90
github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc015e32000, 0x32bbdd73f4db33b6, 0x267ba816a65a56d6, 0x48f0e6cb047b9bbb, 0xb2fb675c2064d90f, 0x1ae8098, 0xc258749230, 0xc4c43b9090, 0x0, 0x1ad0468, ...)
```

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by jayboy-mabushi** [comment]
@guagualvcha were you able to resolve the issue?

**Comment by guagualvcha** [comment]
solved in https://github.com/binance-chain/bsc/releases/tag/v1.1.0
