### ISSUE TITLE
panic on testnet

### ISSUE THREAD

**Issue by MarlikAlmighty** [binance-chain/bsc#242]
```
panic: expected tx hash 0x51d746fbcd2139556962af1a47d9f80abd429640ed9b56ca449b07cb73a296b2, get 0x1c9607e24322e7228506aeb06da4d07b5978be74e9d0799f30b09b3581474b2d

goroutine 1518 [running]:
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).Finalize(0xc0002f4000, 0x1afafd8, 0xc0000d4c80, 0xc05fdb8b40, 0xc038ecdd40, 0xc0553b6180, 0x25e1c30, 0x0, 0x0, 0xc0553b6150, ...)
	github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:708 +0x10fb
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0001f5540, 0xc025ef7cb0, 0xc038ecdd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/state_processor.go:106 +0xe78
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc0000d4c80, 0xc03169c000, 0x800, 0x800, 0x635ee0a7a0024101, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:1876 +0x1183
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc0000d4c80, 0xc03169c000, 0x800, 0x800, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:1647 +0xcd3
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc015324000, 0xc03133c000, 0x800, 0x800, 0x800, 0x0)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1745 +0x50b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc015324000, 0xc22de14b41475a42, 0x7e4cbd16cd7221f6)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1719 +0x7d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc015324000, 0xc018326d80, 0xc018049d20)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:595 +0x5b
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:595 +0xaf

```

**Comment by dancespiele** [comment]
I have the same issue with testnet, how did you resolve the issue @MarlikAlmighty ?

**Comment by MarlikAlmighty** [comment]
> I have the same issue with testnet, how did you resolve the issue @MarlikAlmighty ?

I gave it up for now. After several days of synchronization, my nerves did not survive))
