### ISSUE TITLE
Tests fail with panic: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0 [recovered]

### ISSUE THREAD

**Issue by dimitar-petrov** [binance-chain/bsc#252]
#### System information

Geth version: develop
OS & Version: Archlinux: 5.12.5-arch1-1
Commit hash : b67a129

#### Expected behaviour
Tests should be able to run

#### Actual behaviour
Tests fail

#### Steps to reproduce the behaviour
1. Clone latest master
2. Run `make test` or specific test `go test -v ./eth/filters/... --run "TestBlockSubscription$"`

#### Backtrace
````
$ go test -v ./eth/filters/... --run "TestBlockSubscription$"
=== RUN   TestBlockSubscription
=== PAUSE TestBlockSubscription
=== CONT  TestBlockSubscription
INFO [05-25|13:00:27.169] Persisted trie from memory database      nodes=0 size=0.00B time="5.696�s" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
here
--- FAIL: TestBlockSubscription (0.00s)
panic: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0 [recovered]
        panic: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0

goroutine 42 [running]:
testing.tRunner.func1.2(0xe62e80, 0xc000195770)
        /usr/lib/go/src/testing/testing.go:1144 +0x34b
testing.tRunner.func1(0xc000102d80)
        /usr/lib/go/src/testing/testing.go:1147 +0x4b6
panic(0xe62e80, 0xc000195770)
        /usr/lib/go/src/runtime/panic.go:972 +0x1d4
github.com/ethereum/go-ethereum/core.(*Genesis).MustCommit(...)
        /home/dpetrov/develop/go/bsc/core/genesis.go:337
github.com/ethereum/go-ethereum/eth/filters.TestBlockSubscription(0xc000102d80)
        /home/dpetrov/develop/go/bsc/eth/filters/filter_system_test.go:172 +0x797
testing.tRunner(0xc000102d80, 0x11fc498)
        /usr/lib/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1239 +0x2b3
FAIL    github.com/ethereum/go-ethereum/eth/filters     0.049s
FAIL
````

**Comment by guagualvcha** [comment]
This is fixed in latest release.
