### ISSUE TITLE
Block time in BSC

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#347]
Hello Everyone,
Starting private local network in BSC. The block can be generated <1s. But the block time in BSC is 3s.
How is it possible?
Can i add any parameter in genesis.json file?

**Comment by guagualvcha** [comment]
Yes, you can change the `"parlia": {      "period": 3,      "epoch": 200    }` into `"parlia": {      "period": 1,      "epoch": 200    }`, then the blocking time would be 1 second

**Comment by jianchengwang** [comment]
> Yes, you can change the `"parlia": { "period": 3, "epoch": 200 }` into `"parlia": { "period": 1, "epoch": 200 }`, then the blocking time would be 1 second

I set `period=0` when submitting the transaction, bsc-validator-node seal block success, but bsc-rpc-node will be crashed by under error logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf977b1]

goroutine 46 [running]:
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).applyTransaction(0xc000d5af00, 0x0, 0x0, 0x0, 0xc001d2fc50, 0x7fffffffffffffff, 0xc0017c8940, 0xc0017c8920, 0x0, 0x0, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1181 +0x14f1
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).distributeToSystem(0xc000d5af00, 0xc0017c8920, 0xc000c9c780, 0xc0012358c0, 0x1b32878, 0xc0017c8840, 0xc00015c318, 0xc00015c360, 0x0, 0xc001235a90, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1130 +0x1e5
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).distributeIncoming(0xc000d5af00, 0x0, 0x0, 0xc000000000, 0xc000c9c780, 0xc0012358c0, 0x1b32878, 0xc0017c8840, 0xc00015c318, 0xc00015c360, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:1060 +0x526
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).FinalizeAndAssemble(0xc000d5af00, 0x1b4a930, 0xc000d9c880, 0xc0012358c0, 0xc000c9c780, 0xc001d673b0, 0x2, 0x2, 0x263e138, 0x0, ...)
  github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:758 +0x496
github.com/ethereum/go-ethereum/miner.(*worker).commit(0xc000c36000, 0x263e138, 0x0, 0x0, 0x0, 0x0, 0xc06b218da3b9e3a6, 0x1e3b66e611, 0x2609d00, 0x203000, ...)
  github.com/ethereum/go-ethereum/miner/worker.go:997 +0x10a
github.com/ethereum/go-ethereum/miner.(*worker).commitNewWork(0xc000c36000, 0x0, 0x2609d01, 0x61cc0eb6)
  github.com/ethereum/go-ethereum/miner/worker.go:990 +0xa45
github.com/ethereum/go-ethereum/miner.(*worker).mainLoop(0xc000c36000)
  github.com/ethereum/go-ethereum/miner/worker.go:526 +0x3a5
created by github.com/ethereum/go-ethereum/miner.newWorker
  github.com/ethereum/go-ethereum/miner/worker.go:234 +0x532
```
I don't know this is a bug or do I want to set `period=0` i need to do some other config
