### ISSUE TITLE
Unexpected panic 

### ISSUE THREAD

**Issue by greensea** [binance-chain/bsc#404]
#### System information

Geth version: `1.1.2`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
No panic.

#### Actual behaviour
Panic.

#### Steps to reproduce the behaviour
Run geth, after few days, it panics.

#### Backtrace

````
INFO [09-01|10:32:33.306] Imported new chain segment               blocks=1    txs=322     mgas=48.075  elapsed=561.017ms     mgasps=85.693   number=10,523,890 hash=9b8458..58e580 age=2m13s     dirty=555.53MiB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf624b5]

goroutine 431384081 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc00c8521e0, 0xc0225d6000, 0x0, 0xa0951c, 0x9f3569, 0x9f3569, 0x0, 0x1b00940)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:988 +0x6d5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00c8521e0, 0xc0225d6000, 0xc22b8bed80, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:840 +0x3a5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00c8521e0, 0xc0225d6000, 0xe4670e8b1625fe46, 0xdd3a63f12b48b638, 0xe79b128b086df2d2, 0x25a422e0ebf1791b, 0xc089f6c640, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:497 +0x516
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc00c8521e0, 0xc0d5cd4080, 0x40, 0xe4670e8b1625fe46, 0xdd3a63f12b48b638, 0xe79b128b086df2d2, 0x25a422e0ebf1791b, 0xc089f6c640, 0xc000000000, 0x0, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:453 +0x3b1
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00c8521e0, 0xc0d5cd4080, 0x40, 0xe4670e8b1625fe46, 0xdd3a63f12b48b638, 0xe79b128b086df2d2, 0x25a422e0ebf1791b, 0xc089f6c640, 0x0, 0x14f1880, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:348 +0x8c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc00d1a3400, 0xc1339a1100, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/sync.go:325 +0x125
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc000229020, 0xc1339a1100)
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x76

````

When submitting logs: please submit them as text and not screenshots.

**Comment by profforg** [comment]
same as #388 probably

**Comment by greensea** [comment]
Today it panics again. The backtrace is the same.

```
INFO [09-02|07:23:47.592] Unindexed transactions                   blocks=1    txs=184     tail=8,198,568 elapsed=1.988ms
INFO [09-02|07:23:49.253] Imported new chain segment               blocks=1    txs=226     mgas=36.559  elapsed=1.654s      mgasps=22.092  number=10,548,568 hash=363023..e3cf2e age=1m45s    dirty=462.44MiB
INFO [09-02|07:23:49.257] Unindexed transactions                   blocks=1    txs=112     tail=8,198,569 elapsed=3.607ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf624b5]

goroutine 68655702 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc00ae5d4a0, 0xc1172560f0, 0x0, 0xa0f576, 0x9f95c6, 0x9f95c6, 0x0, 0x1b00940)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:988 +0x6d5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00ae5d4a0, 0xc1172560f0, 0xc0c9701d40, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:840 +0x3a5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00ae5d4a0, 0xc1172560f0, 0x1b18b30598150ce7, 0xeb79ad2b9fda95a6, 0xe662dd12a04ded12, 0xe3c88872507a13dd, 0xc088fe2980, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:497 +0x516
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc00ae5d4a0, 0xc06627f080, 0x40, 0x1b18b30598150ce7, 0xeb79ad2b9fda95a6, 0xe662dd12a04ded12, 0xe3c88872507a13dd, 0xc088fe2980, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:453 +0x3b1
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00ae5d4a0, 0xc06627f080, 0x40, 0x1b18b30598150ce7, 0xeb79ad2b9fda95a6, 0xe662dd12a04ded12, 0xe3c88872507a13dd, 0xc088fe2980, 0x0, 0x14f1880, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:348 +0x8c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc00b936100, 0xc2751fb040, 0x0, 0x486f81)
        github.com/ethereum/go-ethereum/eth/sync.go:325 +0x125
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc0074a8cc0, 0xc2751fb040)
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x76
```
