### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by urkishan** [binance-chain/bsc#413]
#### System information

Geth
Version: 1.1.2
Git Commit: c4f931212903b3ee8495c36ac374340aec4ac269
Git Commit Date: 20210825
Architecture: amd64
Go Version: go1.15.14
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/usr/local/go

OS & Version: Ubuntu

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf69da7]

goroutine 48952661 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc00000c960, 0xc0704de780, 0x0, 0xa369c4, 0xa20a31, 0xa20a31, 0x0, 0x1b0b620)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:988 +0x6e7
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc00000c960, 0xc0704de780, 0xc083fa2240, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:840 +0x3a5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc00000c960, 0xc0704de780, 0x7f2ea868f6d1c0e2, 0xbcf30caadaafe14f, 0x42e5f76be7303a65, 0xb5db9538a67122bd, 0xc3b1e9e000, 0x0, 0x0)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:497 +0x516
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc00000c960, 0xc0f41f28c0, 0x40, 0x7f2ea868f6d1c0e2, 0xbcf30caadaafe14f, 0x42e5f76be7303a65, 0xb5db9538a67122bd, 0xc3b1e9e000, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:453 +0x3b1
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc00000c960, 0xc0f41f28c0, 0x40, 0x7f2ea868f6d1c0e2, 0xbcf30caadaafe14f, 0x42e5f76be7303a65, 0xb5db9538a67122bd, 0xc3b1e9e000, 0x0, 0x14fbb40, ...)
        github.com/ethereum/go-ethereum/eth/downloader/downloader.go:348 +0x8c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc042f98000, 0xc170b50c00, 0x0, 0x487101)
        github.com/ethereum/go-ethereum/eth/sync.go:325 +0x125
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc040e07080, 0xc170b50c00)
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        github.com/ethereum/go-ethereum/eth/sync.go:301 +0x76
```

My node crashed last night, is it normal behaviour?

**Comment by perwpqwe** [comment]
header := d.lightchain.GetHeaderByHash(h) // Independent of sync mode, header surely exists
if header == nil {
	// p.log.Error("header not found", "number", **header.Number, "hash", header.Hash(), "request"**, check)
	// return 0, fmt.Errorf("%w: header no found (%d)", errBadPeer, header.Number)
	return 0, fmt.Errorf("%w: header no found", errBadPeer)
}

**Comment by tino-web** [comment]
Same here

`
![image](https://user-images.githubusercontent.com/8428164/133633200-41945e93-f976-4167-a98a-dca5a81db216.png)
`

**Comment by seonggwonyoon** [comment]
This problem repeats to me every 5-7 days.
I hope it gets stabilized soon.
@j75689 @yutianwu @guagualvcha

**Comment by guagualvcha** [comment]
Already fixed.
