### ISSUE TITLE
Panic in findAncestorBinarySearch()

### ISSUE THREAD

**Issue by greensea** [binance-chain/bsc#421]
#### System information

Geth
Version: 1.1.2
Git Commit: bca96785476e66816bca30eb8050cd3e527efeba
Git Commit Date: 20210906
Architecture: amd64
Go Version: go1.13.1
Operating System: linux
GOPATH=/home/gs/go
GOROOT=/usr/local/go

#### Expected behaviour

No panic.

#### Actual behaviour

It panics.

#### Steps to reproduce the behaviour

Run geth for few days, then it panics.

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xf7444a]

goroutine 22127309 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0xc0052f6000, 0xc050475770, 0x0, 0xa700e7, 0xa5a12d, 0xa5a12d, 0x0, 0x1bfe540)
        github.com/ethereum/go-ethereum@/eth/downloader/downloader.go:989 +0xafa
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0052f6000, 0xc050475770, 0xc14c260000, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum@/eth/downloader/downloader.go:840 +0x383
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0052f6000, 0xc050475770, 0x13de941776be1b52, 0x990a4f31789533e, 0x33e2bcb40abc5b2c, 0x1ca61b1fae300bc5, 0xc206ab94c0, 0x0, 0x0)
        github.com/ethereum/go-ethereum@/eth/downloader/downloader.go:497 +0x518
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0052f6000, 0xc15ec13840, 0x40, 0x13de941776be1b52, 0x990a4f31789533e, 0x33e2bcb40abc5b2c, 0x1ca61b1fae300bc5, 0xc206ab94c0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum@/eth/downloader/downloader.go:453 +0x3f5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0052f6000, 0xc15ec13840, 0x40, 0x13de941776be1b52, 0x990a4f31789533e, 0x33e2bcb40abc5b2c, 0x1ca61b1fae300bc5, 0xc206ab94c0, 0xc000000000, 0x1c3ae00, ...)
        github.com/ethereum/go-ethereum@/eth/downloader/downloader.go:348 +0x8c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0xc0017ac600, 0xc1543e87c0, 0x108e81d, 0xc0017ac600)
        github.com/ethereum/go-ethereum@/eth/sync.go:325 +0x117
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0xc00508e8d0, 0xc1543e87c0)
        github.com/ethereum/go-ethereum@/eth/sync.go:301 +0x38
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        github.com/ethereum/go-ethereum@/eth/sync.go:301 +0x7a
````

This issue is possibly related to #404, the backtraces are the same. 
After #404 is fixed, I checkout the latest code and build it. This dev version is more stable than 1.1.2 release version, but it still panics at the morning today.

**Comment by guagualvcha** [comment]
It is fixed in latest release.
