### ISSUE TITLE
crashed with "panic: deletion not supported"

### ISSUE THREAD

**Issue by nining** [binance-chain/bsc#505]
#### System information

Geth version: `v1.1.3`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
running smoothly.

#### Actual behaviour
every time crashed after launched several hours.

#### Backtrace

````
panic: deletion not supported

goroutine 1275749 [running]:
github.com/ethereum/go-ethereum/trie.(*StackTrie).TryUpdate(0xc04d5e4e50, 0xc1b27e7800, 0x20, 0x20, 0x261f3f8, 0x0, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/trie/stacktrie.go:194 +0xd2
github.com/ethereum/go-ethereum/trie.VerifyRangeProof(0xd7abae715e5aac05, 0x36e1c8581368eee5, 0xcf8b950979d40254, 0x4d0f531068fe3c2a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/trie/proof.go:486 +0x1f2
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).OnStorage(0xc00000cf00, 0x1b2ce50, 0xc23c3f6940, 0x13730d98f87c0ce1, 0xc18d292c00, 0x40, 0x40, 0xc18d293200, 0x40, 0x40, ...)
	github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:2423 +0x893
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).DeliverSnapPacket(0xc00000d0e0, 0xc23c3f6940, 0x1b12de8, 0xc1ab72d800, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:2044 +0x472
github.com/ethereum/go-ethereum/eth.(*snapHandler).Handle(0xc0003a58c0, 0xc23c3f6940, 0x1b12de8, 0xc1ab72d800, 0x3, 0x13730d98f87c0ce1)
	github.com/ethereum/go-ethereum/eth/handler_snap.go:49 +0x50
github.com/ethereum/go-ethereum/eth/protocols/snap.handleMessage(0x1b247a0, 0xc0003a58c0, 0xc23c3f6940, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/protocols/snap/handler.go:373 +0x21ea
github.com/ethereum/go-ethereum/eth/protocols/snap.handle(0x1b247a0, 0xc0003a58c0, 0xc23c3f6940, 0xc011cf2580, 0x1994fe0)
	github.com/ethereum/go-ethereum/eth/protocols/snap/handler.go:123 +0x45
github.com/ethereum/go-ethereum/eth/protocols/snap.MakeProtocols.func2.1(0xc23c3f6940, 0xc23c3f6940, 0x0)
	github.com/ethereum/go-ethereum/eth/protocols/snap/handler.go:103 +0x3d
github.com/ethereum/go-ethereum/eth.(*handler).runSnapExtension(0xc0003a58c0, 0xc23c3f6940, 0xc19dce8948, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/handler.go:374 +0x1e6
github.com/ethereum/go-ethereum/eth.(*snapHandler).RunPeer(0xc0003a58c0, 0xc23c3f6940, 0xc19dce8948, 0xc0a09ef860, 0xc23c3f6940)
	github.com/ethereum/go-ethereum/eth/handler_snap.go:33 +0x3f
github.com/ethereum/go-ethereum/eth/protocols/snap.MakeProtocols.func2(0xc2225e2780, 0x1b13298, 0xc0a09ef860, 0xc2335ec7a8, 0x0)
	github.com/ethereum/go-ethereum/eth/protocols/snap/handler.go:102 +0xbb
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc2225e2780, 0xc0a09ef860, 0x1b13298, 0xc0a09ef860)
	github.com/ethereum/go-ethereum/p2p/peer.go:396 +0x98
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	github.com/ethereum/go-ethereum/p2p/peer.go:394 +0x205
````

When submitting logs: please submit them as text and not screenshots.

**Comment by freelancedeveloper025** [comment]
me also faced same issue

**Comment by vrogojin** [comment]
I have same issue. Reported here #475

**Comment by KeefeL** [comment]
Same issue to #475, I'm going to close this one.
