### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x838c57

### ISSUE THREAD

**Issue by vrogojin** [binance-chain/bsc#512]
#### System information

Geth version: `1.1.2`
OS & Version: Ubuntu 20.04.3 LTS
Geth
Version: 1.1.2 (binary pre-build as of 22.10.2021)
Architecture: amd64

#### Expected behaviour
No crash

#### Actual behaviour
Was running geth on four different unrelated machines with same OS and geth version. All nodes crashed at around same time 2011-11-03 07:52:37 UTC

#### Steps to reproduce the behaviour
```
geth --syncmode=snap --config ./config.toml --datadir <datadir>  --cache 18000 --rpc --http.port 9545 --http.corsdomain "*" --http.api "eth,web3,personal,net,txpool" --ws --ws.port 8546 --ws.origins "*" \
    --ws.api "eth,web3,personal,net,txpool" --rpc.allow-unprotected-txs --txlookuplimit 0 console
```
Keep geth running for few hours to few weeks

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x838c57]

goroutine 2632143136 [running]:
github.com/ethereum/go-ethereum/core/state.(*triePrefetcher).close(0x0)
        github.com/ethereum/go-ethereum/core/state/trie_prefetcher.go:106 +0x37
github.com/ethereum/go-ethereum/core/state.(*StateDB).IntermediateRoot.func1(0xc11d340000)
        github.com/ethereum/go-ethereum/core/state/statedb.go:948 +0x2f
github.com/ethereum/go-ethereum/core/state.(*StateDB).IntermediateRoot(0xc11d340000, 0xc3ff7fc301, 0xcaeb2198e8949a07, 0x1f2169ff974c24d, 0x204a5b7cccd7e234, 0xe97a0ca285a23484)
        github.com/ethereum/go-ethereum/core/state/statedb.go:1034 +0x765
github.com/ethereum/go-ethereum/core.(*BlockValidator).ValidateState.func3(0x0, 0x1)
        github.com/ethereum/go-ethereum/core/block_validator.go:135 +0x78
github.com/ethereum/go-ethereum/core.(*BlockValidator).ValidateState.func4(0xc3204ba2a0, 0xc3ff7fc380)
        github.com/ethereum/go-ethereum/core/block_validator.go:147 +0x27
created by github.com/ethereum/go-ethereum/core.(*BlockValidator).ValidateState
        github.com/ethereum/go-ethereum/core/block_validator.go:146 +0x1e5
````

Reason of crash apparently is "BAD BLOCK". See [log file](https://pastebin.com/KtfMBm1z).

**Comment by KeefeL** [comment]
I think this has been fixed by #491 , thanks for your report.
