### ISSUE TITLE
Time out error during Deployment in Binance Smart Chain

### ISSUE THREAD

**Issue by hyunkicho** [binance-chain/bsc#98]
I got an error while deploying contract in Binance Smart Chain

plz help me if anybody knows it

error message looks like this

```
   Deploying 'WhitePaperInterestRateModel'
   ---------------------------------------
   > transaction hash:    0xa24026a456f81238422b262cc49bcb9ee494997b70ea8d41c092710f98b27d50
   ⠧ Blocks: 23           Seconds: 69Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  code: -32603,
  message: 'ETIMEDOUT',
  data: { originalError: { code: 'ETIMEDOUT', connect: true } },
  stack: 'Error: ETIMEDOUT\n' +
    '    at Timeout.<anonymous> (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/request/request.js:848:19)\n' +
    '    at listOnTimeout (node:internal/timers:556:17)\n' +
    '    at processTimers (node:internal/timers:499:7)'
})
    at new NodeError (node:internal/errors:329:5)
    at Web3ProviderEngine.emit (node:events:368:17)
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/async/internal/once.js:12:16
    at replenish (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/async/eachLimit.js:43:36)
    at /Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:36:21)
    at self.callback (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/request/request.js:185:22)
    at Request.emit (node:events:379:20)
    at Timeout.<anonymous> (/Users/hyunki/Desktop/compound/compound_test/truffle-compound-bsc/venus-protocol/node_modules/request/request.js:851:16)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```

truffle-config.js

```
    testnet: {
      provider: () => new HDWalletProvider(mnemonic, `https://data-seed-prebsc-1-s2.binance.org:8545/`),
      network_id: 97,
      gas: 20000000,        // Ropsten has a lower block limit than mainnet
      gasPrice: 20000000000,  // 20 gwei (in wei) (default: 100 gwei)
      confirmations: 1,
      timeoutBlocks: 50000,
      skipDryRun: true
    },
```

**Comment by fedecaccia** [comment]
Hi @guagualvcha thanks for the prev response. The workaround is always to test in other EVM compatible blockchians. Has the team solved this issue? Sometimes, during deployment, Im also experimenting "Bad Gateway" errors.

**Comment by guagualvcha** [comment]
closing since it is not node related.

**Comment by nmsteve** [comment]
I am experiencing the same issue both in Bsc and Cronos. The networks have no endpoints on Alchemy and Infura. am thinking the require a very strong internet connecting
